### ISSUE TITLE
More than one file was found with OS independent path 'lib/armeabi-v7a/libfreetype.so'

### ISSUE THREAD

**Issue by gantulgana93** [flyskywhy/react-native-particles-bg#1]
Any help please

**Comment by flyskywhy** [comment]
duplicate of https://github.com/flyskywhy/react-native-gcanvas/issues/6

**Comment by flyskywhy** [comment]
Fixed with  react-native-particles-bg@3.0.3 and @flyskywhy/react-native-gcanvas@2.3.2
