### ISSUE TITLE
 ERROR  Invariant Violation: requireNativeComponent: "GCanvasView" was not found in the UIManager.

### ISSUE THREAD

**Issue by Ayomide57** [flyskywhy/react-native-particles-bg#2]
![Screenshot_1623844947](https://user-images.githubusercontent.com/39005838/122215496-3343bb00-cea3-11eb-989a-23495b1f7d6c.png)
![Screenshot 2021-06-16 at 13 03 28](https://user-images.githubusercontent.com/39005838/122215604-50788980-cea3-11eb-9cf6-38385184866a.png)

**Comment by Ayomide57** [comment]
error appear after installing GcanvasView
![Screenshot 2021-06-16 at 11 53 29](https://user-images.githubusercontent.com/39005838/122479747-7f861c80-cfc3-11eb-991a-f3d290b0e933.png)

**Comment by Ayomide57** [comment]
Os is android

**Comment by flyskywhy** [comment]
And RN version?

**Comment by flyskywhy** [comment]
The `requireNativeComponent: "GCanvasView" was not found` problem is fixed.

The `installing GcanvasView` is duplicated with https://github.com/flyskywhy/react-native-gcanvas/issues/19
