### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by axwell** [flyskywhy/react-native-particles-bg#3]
Hello,
I can't use the package on the latest react.

npm i react-native-particles-bg
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: playtest@0.0.1
npm ERR! Found: react-native@0.67.2
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.67.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.60.6" from react-native-particles-bg@3.0.3
npm ERR! node_modules/react-native-particles-bg
npm ERR!   react-native-particles-bg@"*" from the root project

**Comment by flyskywhy** [comment]
Ref to https://github.com/flyskywhy/react-native-usb-serialport/issues/2#issuecomment-872210795 , maybe you need

```
use npm version which is below 7
```
or
```
npm install react-native-particles-bg --legacy-peer-deps
```
